// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nytnalwhuifcqfmuxqjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dG5hbHdodWlmY3FmbXV4cWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNjg0NjAsImV4cCI6MjA1Mzg0NDQ2MH0.d5Hts--BgdyvNPCmHcd2thguoHJZoOcjmQe4eBwMfv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);